import type { Categories, Category } from '~/constants/categories'
import type { LOADING } from '~/store/slices/constants'
import type { IPlayer } from '../players/player'

export type Difficulty = 0 | 1 | 2 | 3 | 4 | 5

export type InitialState = {
    isLoading: LOADING
    rounds: number
    round: number
    points: number
    difficulty: Difficulty
    questionRound: number
    disguisedPlayer: IPlayer | null
    votingItem: string
    item: Categories | null
    mostVoted: IPlayer | null
    category: Category | null
}

export const name = 'game'

export const ON_CHANGE_ROUNDS = 'ON_CHANGE_ROUNDS'
export const ON_CHANGE_ROUNDS_SUCCESS = 'ON_CHANGE_ROUNDS_SUCCESS'
export const ON_CHANGE_ROUNDS_FAIL = 'ON_CHANGE_ROUNDS_FAIL'

export const ON_CHANGE_POINTS = 'ON_CHANGE_POINTS'
export const ON_CHANGE_POINTS_SUCCESS = 'ON_CHANGE_POINTS_SUCCESS'
export const ON_CHANGE_POINTS_FAIL = 'ON_CHANGE_POINTS_FAIL'

export const ON_CHANGE_QUESTION_ROUND = 'ON_CHANGE_QUESTION_ROUND'
export const ON_CHANGE_QUESTION_ROUND_SUCCESS = 'ON_CHANGE_QUESTION_ROUND_SUCCESS'
export const ON_CHANGE_QUESTION_ROUND_FAIL = 'ON_CHANGE_QUESTION_ROUND_FAIL'

export const ON_GENERATE_DISGUISED = 'ON_GENERATE_DISGUISED'
export const ON_GENERATE_DISGUISED_SUCCESS = 'ON_GENERATE_DISGUISED_SUCCESS'
export const ON_GENERATE_DISGUISED_FAIL = 'ON_GENERATE_DISGUISED_FAIL'

export const ON_VOTING_ITEM = 'ON_VOTING_ITEM'
export const ON_VOTING_ITEM_SUCCESS = 'ON_VOTING_ITEM_SUCCESS'
export const ON_VOTING_ITEM_FAIL = 'ON_VOTING_ITEM_FAIL'

export const ON_SCORE_PLAYERS = 'ON_SCORE_PLAYERS'
export const ON_SCORE_PLAYERS_SUCCESS = 'ON_SCORE_PLAYERS_SUCCESS'
export const ON_SCORE_PLAYERS_FAIL = 'ON_SCORE_PLAYERS_FAIL'

export const ON_RESET_GAME = 'ON_RESET_GAME'
export const ON_RESET_GAME_SUCCESS = 'ON_RESET_GAME_SUCCESS'
export const ON_RESET_GAME_FAIL = 'ON_RESET_GAME_FAIL'

export const ON_VOTE_IN_THE_DISGUISED = 'ON_VOTE_IN_THE_DISGUISED'
export const ON_VOTE_IN_THE_DISGUISED_SUCCESS = 'ON_VOTE_IN_THE_DISGUISED_SUCCESS'
export const ON_VOTE_IN_THE_DISGUISED_FAIL = 'ON_VOTE_IN_THE_DISGUISED_FAIL'

export const ON_CHANGE_PLAY_ROUND = 'ON_CHANGE_PLAY_ROUND'
export const ON_CHANGE_PLAY_ROUND_SUCCESS = 'ON_CHANGE_PLAY_ROUND_SUCCESS'
export const ON_CHANGE_PLAY_ROUND_FAIL = 'ON_CHANGE_PLAY_ROUND_FAIL'

export const ON_CHANGE_MOST_VOTED = 'ON_CHANGE_MOST_VOTED'
export const ON_CHANGE_MOST_VOTED_SUCCESS = 'ON_CHANGE_MOST_VOTED_SUCCESS'
export const ON_CHANGE_MOST_VOTED_FAIL = 'ON_CHANGE_MOST_VOTED_FAIL'

export const ON_GENERATE_ITEM = 'ON_GENERATE_ITEM'
export const ON_GENERATE_ITEM_SUCCESS = 'ON_GENERATE_ITEM_SUCCESS'
export const ON_GENERATE_ITEM_FAIL = 'ON_GENERATE_ITEM_FAIL'

export const ON_CHANGE_DIFFICULTY = 'ON_CHANGE_DIFFICULTY'
export const ON_CHANGE_DIFFICULTY_SUCCESS = 'ON_CHANGE_DIFFICULTY_SUCCESS'
export const ON_CHANGE_DIFFICULTY_FAIL = 'ON_CHANGE_DIFFICULTY_FAIL'

export const ON_CHANGE_CATEGORY = 'ON_CHANGE_CATEGORY'
export const ON_CHANGE_CATEGORY_SUCCESS = 'ON_CHANGE_CATEGORY_SUCCESS'
export const ON_CHANGE_CATEGORY_FAIL = 'ON_CHANGE_CATEGORY_FAIL'

export const ACTION_CHANGE_CATEGORY = `${name}/${ON_CHANGE_CATEGORY}`
export const ACTION_CHANGE_CATEGORY_SUCCESS = `${name}/${ON_CHANGE_CATEGORY_SUCCESS}`
export const ACTION_CHANGE_CATEGORY_FAIL = `${name}/${ON_CHANGE_CATEGORY_FAIL}`

export const ACTION_CHANGE_ROUNDS = `${name}/${ON_CHANGE_ROUNDS}`
export const ACTION_CHANGE_ROUNDS_SUCCESS = `${name}/${ON_CHANGE_ROUNDS_SUCCESS}`
export const ACTION_CHANGE_ROUNDS_FAIL = `${name}/${ON_CHANGE_ROUNDS_FAIL}`

export const ACTION_CHANGE_POINTS = `${name}/${ON_CHANGE_POINTS}`
export const ACTION_CHANGE_POINTS_SUCCESS = `${name}/${ON_CHANGE_POINTS_SUCCESS}`
export const ACTION_CHANGE_POINTS_FAIL = `${name}/${ON_CHANGE_POINTS_FAIL}`

export const ACTION_CHANGE_QUESTION_ROUND = `${name}/${ON_CHANGE_QUESTION_ROUND}`
export const ACTION_CHANGE_QUESTION_ROUND_SUCCESS = `${name}/${ON_CHANGE_QUESTION_ROUND_SUCCESS}`
export const ACTION_CHANGE_QUESTION_ROUND_FAIL = `${name}/${ON_CHANGE_QUESTION_ROUND_FAIL}`

export const ACTION_GENERATE_DISGUISED = `${name}/${ON_GENERATE_DISGUISED}`
export const ACTION_GENERATE_DISGUISED_SUCCESS = `${name}/${ON_GENERATE_DISGUISED_SUCCESS}`
export const ACTION_GENERATE_DISGUISED_FAIL = `${name}/${ON_GENERATE_DISGUISED_FAIL}`

export const ACTION_VOTING_ITEM = `${name}/${ON_VOTING_ITEM}`
export const ACTION_VOTING_ITEM_SUCCESS = `${name}/${ON_VOTING_ITEM_SUCCESS}`
export const ACTION_VOTING_ITEM_FAIL = `${name}/${ON_VOTING_ITEM_FAIL}`

export const ACTION_SCORE_PLAYERS = `${name}/${ON_SCORE_PLAYERS}`
export const ACTION_SCORE_PLAYERS_SUCCESS = `${name}/${ON_SCORE_PLAYERS_SUCCESS}`
export const ACTION_SCORE_PLAYERS_FAIL = `${name}/${ON_SCORE_PLAYERS_FAIL}`

export const ACTION_RESET_GAME = `${name}/${ON_RESET_GAME}`
export const ACTION_RESET_GAME_SUCCESS = `${name}/${ON_RESET_GAME_SUCCESS}`
export const ACTION_RESET_GAME_FAIL = `${name}/${ON_RESET_GAME_FAIL}`

export const ACTION_VOTE_IN_THE_DISGUISED = `${name}/${ON_VOTE_IN_THE_DISGUISED}`
export const ACTION_VOTE_IN_THE_DISGUISED_SUCCESS = `${name}/${ON_VOTE_IN_THE_DISGUISED_SUCCESS}`
export const ACTION_VOTE_IN_THE_DISGUISED_FAIL = `${name}/${ON_VOTE_IN_THE_DISGUISED_FAIL}`

export const ACTION_CHANGE_PLAY_ROUND = `${name}/${ON_CHANGE_PLAY_ROUND}`
export const ACTION_CHANGE_PLAY_ROUND_SUCCESS = `${name}/${ON_CHANGE_PLAY_ROUND_SUCCESS}`
export const ACTION_CHANGE_PLAY_ROUND_FAIL = `${name}/${ON_CHANGE_PLAY_ROUND_FAIL}`

export const ACTION_CHANGE_MOST_VOTED = `${name}/${ON_CHANGE_MOST_VOTED}`
export const ACTION_CHANGE_MOST_VOTED_SUCCESS = `${name}/${ON_CHANGE_MOST_VOTED_SUCCESS}`
export const ACTION_CHANGE_MOST_VOTED_FAIL = `${name}/${ON_CHANGE_MOST_VOTED_FAIL}`

export const ACTION_GENERATE_ITEM = `${name}/${ON_GENERATE_ITEM}`
export const ACTION_GENERATE_ITEM_SUCCESS = `${name}/${ON_GENERATE_ITEM_SUCCESS}`
export const ACTION_GENERATE_ITEM_FAIL = `${name}/${ON_GENERATE_ITEM_FAIL}`

export const ACTION_CHANGE_DIFFICULTY = `${name}/${ON_CHANGE_DIFFICULTY}`
export const ACTION_CHANGE_DIFFICULTY_SUCCESS = `${name}/${ON_CHANGE_DIFFICULTY_SUCCESS}`
export const ACTION_CHANGE_DIFFICULTY_FAIL = `${name}/${ON_CHANGE_DIFFICULTY_FAIL}`
