import type { LOADING } from '~/store/slices/constants'
import type { Player } from './player'

export type InitialState = {
    isLoading: LOADING
    players: (typeof Player)[]
}

export const name = 'players'

export const ON_CHANGE_PLAYERS = 'ON_CHANGE_PLAYERS'
export const ON_CHANGE_PLAYERS_SUCCESS = 'ON_CHANGE_PLAYERS_SUCCESS'
export const ON_CHANGE_PLAYERS_FAIL = 'ON_CHANGE_PLAYERS_FAIL'

export const ON_ADD_PLAYERS = 'ON_ADD_PLAYERS'
export const ON_ADD_PLAYERS_SUCCESS = 'ON_ADD_PLAYERS_SUCCESS'
export const ON_ADD_PLAYERS_FAIL = 'ON_ADD_PLAYERS_FAIL'

export const ON_DELETE_PLAYERS = 'ON_DELETE_PLAYERS'
export const ON_DELETE_PLAYERS_SUCCESS = 'ON_DELETE_PLAYERS_SUCCESS'
export const ON_DELETE_PLAYERS_FAIL = 'ON_DELETE_PLAYERS_FAIL'

export const ON_UPDATE_PLAYER_SCORE = 'ON_UPDATE_PLAYER_SCORE'
export const ON_UPDATE_PLAYER_SCORE_SUCCESS = 'ON_UPDATE_PLAYER_SCORE_SUCCESS'
export const ON_UPDATE_PLAYER_SCORE_FAIL = 'ON_UPDATE_PLAYER_SCORE_FAIL'

export const ON_UPDATE_PLAYER_REVEAL = 'ON_UPDATE_PLAYER_REVEAL'
export const ON_UPDATE_PLAYER_REVEAL_SUCCESS = 'ON_UPDATE_PLAYER_REVEAL_SUCCESS'
export const ON_UPDATE_PLAYER_REVEAL_FAIL = 'ON_UPDATE_PLAYER_REVEAL_FAIL'

export const ON_UPDATE_PLAYER_CAN_ANSWER = 'ON_UPDATE_PLAYER_CAN_ANSWER'
export const ON_UPDATE_PLAYER_CAN_ANSWER_SUCCESS =
    'ON_UPDATE_PLAYER_CAN_ANSWER_SUCCESS'
export const ON_UPDATE_PLAYER_CAN_ANSWER_FAIL = 'ON_UPDATE_PLAYER_CAN_ANSWER_FAIL'

export const ON_UPDATE_CAN_PLAYER_VOTE = 'ON_UPDATE_CAN_PLAYER_VOTE'
export const ON_UPDATE_CAN_PLAYER_VOTE_SUCCESS = 'ON_UPDATE_CAN_PLAYER_VOTE_SUCCESS'
export const ON_UPDATE_CAN_PLAYER_VOTE_FAIL = 'ON_UPDATE_CAN_PLAYER_VOTE_FAIL'

export const ON_UPDATE_PLAYER_CAN_ASK = 'ON_UPDATE_PLAYER_CAN_ASK'
export const ON_UPDATE_PLAYER_CAN_ASK_SUCCESS = 'ON_UPDATE_PLAYER_CAN_ASK_SUCCESS'
export const ON_UPDATE_PLAYER_CAN_ASK_FAIL = 'ON_UPDATE_PLAYER_CAN_ASK_FAIL'

export const ON_UPDATE_PLAYER_NAME = 'ON_UPDATE_PLAYER_NAME'
export const ON_UPDATE_PLAYER_NAME_SUCCESS = 'ON_UPDATE_PLAYER_NAME_SUCCESS'
export const ON_UPDATE_PLAYER_NAME_FAIL = 'ON_UPDATE_PLAYER_NAME_FAIL'

export const ON_RESET_PLAYERS = 'ON_RESET_PLAYERS'
export const ON_RESET_PLAYERS_SUCCESS = 'ON_RESET_PLAYERS_SUCCESS'
export const ON_RESET_PLAYERS_FAIL = 'ON_RESET_PLAYERS_FAIL'

export const ON_RESET_VOTING = 'ON_RESET_VOTING'
export const ON_RESET_VOTING_SUCCESS = 'ON_RESET_VOTING_SUCCESS'
export const ON_RESET_VOTING_FAIL = 'ON_RESET_VOTING_FAIL'

export const ACTION_UPDATE_CAN_PLAYER_VOTE = `${name}/${ON_UPDATE_CAN_PLAYER_VOTE}`
export const ACTION_UPDATE_CAN_PLAYER_VOTE_SUCCESS = `${name}/${ON_UPDATE_CAN_PLAYER_VOTE_SUCCESS}`
export const ACTION_UPDATE_CAN_PLAYER_VOTE_FAIL = `${name}/${ON_UPDATE_CAN_PLAYER_VOTE_FAIL}`

export const ACTION_RESET_PLAYERS = `${name}/${ON_RESET_PLAYERS}`
export const ACTION_RESET_PLAYERS_SUCCESS = `${name}/${ON_RESET_PLAYERS_SUCCESS}`
export const ACTION_RESET_PLAYERS_FAIL = `${name}/${ON_RESET_PLAYERS_FAIL}`

export const ACTION_CHANGE_PLAYERS = `${name}/${ON_CHANGE_PLAYERS}`
export const ACTION_CHANGE_PLAYERS_SUCCESS = `${name}/${ON_CHANGE_PLAYERS_SUCCESS}`
export const ACTION_CHANGE_PLAYERS_FAIL = `${name}/${ON_CHANGE_PLAYERS_FAIL}`

export const ACTION_ADD_PLAYERS = `${name}/${ON_ADD_PLAYERS}`
export const ACTION_ADD_PLAYERS_SUCCESS = `${name}/${ON_ADD_PLAYERS_SUCCESS}`
export const ACTION_ADD_PLAYERS_FAIL = `${name}/${ON_ADD_PLAYERS_FAIL}`

export const ACTION_DELETE_PLAYERS = `${name}/${ON_DELETE_PLAYERS}`
export const ACTION_DELETE_PLAYERS_SUCCESS = `${name}/${ON_DELETE_PLAYERS_SUCCESS}`
export const ACTION_DELETE_PLAYERS_FAIL = `${name}/${ON_DELETE_PLAYERS_FAIL}`

export const ACTION_UPDATE_PLAYER_SCORE = `${name}/${ON_UPDATE_PLAYER_SCORE}`
export const ACTION_UPDATE_PLAYER_SCORE_SUCCESS = `${name}/${ON_UPDATE_PLAYER_SCORE_SUCCESS}`
export const ACTION_UPDATE_PLAYER_SCORE_FAIL = `${name}/${ON_UPDATE_PLAYER_SCORE_FAIL}`

export const ACTION_UPDATE_PLAYER_REVEAL = `${name}/${ON_UPDATE_PLAYER_REVEAL}`
export const ACTION_UPDATE_PLAYER_REVEAL_SUCCESS = `${name}/${ON_UPDATE_PLAYER_REVEAL_SUCCESS}`
export const ACTION_UPDATE_PLAYER_REVEAL_FAIL = `${name}/${ON_UPDATE_PLAYER_REVEAL_FAIL}`

export const ACTION_UPDATE_PLAYER_CAN_ANSWER = `${name}/${ON_UPDATE_PLAYER_CAN_ANSWER}`
export const ACTION_UPDATE_PLAYER_CAN_ANSWER_SUCCESS = `${name}/${ON_UPDATE_PLAYER_CAN_ANSWER_SUCCESS}`
export const ACTION_UPDATE_PLAYER_CAN_ANSWER_FAIL = `${name}/${ON_UPDATE_PLAYER_CAN_ANSWER_FAIL}`

export const ACTION_UPDATE_PLAYER_CAN_ASK = `${name}/${ON_UPDATE_PLAYER_CAN_ASK}`
export const ACTION_UPDATE_PLAYER_CAN_ASK_SUCCESS = `${name}/${ON_UPDATE_PLAYER_CAN_ASK_SUCCESS}`
export const ACTION_UPDATE_PLAYER_CAN_ASK_FAIL = `${name}/${ON_UPDATE_PLAYER_CAN_ASK_FAIL}`

export const ACTION_UPDATE_PLAYER_NAME = `${name}/${ON_UPDATE_PLAYER_NAME}`
export const ACTION_UPDATE_PLAYER_NAME_SUCCESS = `${name}/${ON_UPDATE_PLAYER_NAME_SUCCESS}`
export const ACTION_UPDATE_PLAYER_NAME_FAIL = `${name}/${ON_UPDATE_PLAYER_NAME_FAIL}`

export const ACTION_RESET_VOTING = `${name}/${ON_RESET_VOTING}`
export const ACTION_RESET_VOTING_SUCCESS = `${name}/${ON_RESET_VOTING_SUCCESS}`
export const ACTION_RESET_VOTING_FAIL = `${name}/${ON_RESET_VOTING_FAIL}`
